before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: aN/XkKeCeCMbeLqLAqgiFnjfXGCcU7yVggbx6ZyoPxEgYGzik+2aUWpRncv7VryVtPSHhZ3cTudCjetf/SjtRyAINO0Vgks7Ml25Ul63YB5QkGigYipVt29bebJ6Lc6i++/Hli5vaIAg2jWvCQYeP8dWaTwc7XeM/fMIjxr+LN/IXQ4t42G6XeLC6B4AufauJYNre3XblLU6Q05eDJWwVIHOM2Aku4ihPmTU086iAGsglI022v55a/0WcOHmQE/YaCnCkYSDltDF0Lu7leDnlAWsOZEVWDQFjmuECyngtG9y/ajyuPEUC9KLG6/W8GhcRyA04UqKpnwAcZIZ4VIPocfHd3VSyo4MJPo6vI39f7xO/mcjoVKJps4Frs9E7ivstU+czqSijEmp3/9sTfjdw6/a6UEmCKPCW6FlY2tlwC9+kpiZ8ZEwgVLA8YZTymYBzHi1CuuLrNkD32qSDA4IB3HRuxPyr8/alIyM/WjgMuAx8tzuWMxp+Frkr9RvFw6Xrg60lpKzBakdhZEw+vNZ4oDkJwaSsMUgO6CkDcnMe30nz+ZT2drZRDIV8Hzz7RfCIt82uKk0L0BIoVeWFhj1JBB/gNaWN+aI6n667q6lSI5akJErrn7BRXQ4jzibgvqExEJ6FXsFkZDm3O9HXGpevip7CqBCHTUwsTd/yeQLIeE= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
